name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.16.0"
  cupertino_icons: ^0.1.2
  geolocator: ^5.2.0
  http: ^0.12.0+4
  weather_icons: ^2.0.0 # Use the latest version
  wakelock: ^0.1.3+4
  shared_preferences: ^0.5.6+1
  datetime_picker_formfield: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - third_party/openweathericons/
    - third_party/weather-underground-icons/
  uses-material-design: true
  fonts:
    - family: TrenchThin
      fonts:
        - asset: third_party/TrenchThin.ttf

    - family: UbuntuMono
      fonts:
        - asset: third_party/UbuntuMono-R.ttf

    - family: larabiefont
      fonts:
        - asset: third_party/larabiefont-rg.ttf